apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  exportTo:
    - "*"
  hosts:
    - {{ .Values.gateway.hosts | first | quote }}
  gateways:
    - {{ printf "%s/%s" .Values.gateway.namespace .Values.gateway.name }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" .Values.virtualService.service.name .Values.virtualService.namespace }}
            port:
              number: {{ .Values.virtualService.service.port }}
