name: Deploy Frontend to GKE

on:
  workflow_dispatch:

env:
  JFROG_REGISTRY: trialt71vbo.jfrog.io
  IMAGE_NAME: dev-ui-docker-local/user-form-frontend
  HELM_REPO: dev-ui-helm-local
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to JFrog Docker registry
      run: echo "${{ secrets.JFROG_API_KEY }}" | docker login $JFROG_REGISTRY -u "${{ secrets.JFROG_USER }}" --password-stdin

    - name: Build and push Docker image
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker build -t $JFROG_REGISTRY/$IMAGE_NAME:$COMMIT_HASH ./frontend
        docker push $JFROG_REGISTRY/$IMAGE_NAME:$COMMIT_HASH

    - name: Install Helm and JFrog CLI
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/
        jfrog config add jfrog-server --url=https://$JFROG_REGISTRY --user=${{ secrets.JFROG_USER }} --password=${{ secrets.JFROG_API_KEY }} --interactive=false
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Package and upload Helm chart
      run: |
        cd frontend-chart
        helm package .
        jfrog rt u "frontend-*.tgz" $HELM_REPO/

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
   
    - name: Setup Google Cloud SDK and authenticate
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        install_components: gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME \
        --zone $GKE_ZONE \
        --project $GCP_PROJECT_ID

    - name: Create imagePullSecret in GKE
      run: |
        kubectl create secret docker-registry jfrog-secret \
          --docker-server=$JFROG_REGISTRY \
          --docker-username=${{ secrets.JFROG_USER }} \
          --docker-password=${{ secrets.JFROG_API_KEY }} \
          --docker-email=${{ secrets.JFROG_USER }} \
          --namespace front-end --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to GKE using Helm
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        helm upgrade --install frontend ./frontend-chart \
          --namespace front-end \
          --set image.repository=$JFROG_REGISTRY/$IMAGE_NAME \
          --set image.tag=$COMMIT_HASH \
          --set imagePullSecrets[0].name=jfrog-secret \
          --set service.type=LoadBalancer \
          --set service.port=80
          
