name: k8s-secret-creation

on:
  workflow_dispatch:

jobs:
  create-k8s-tls-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with GKE cluster
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --region ${{ secrets.GKE_REGION }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Pull secrets from Secret Manager
      run: |
        gcloud secrets versions access latest --secret=myistio-cert-secret > tls.crt
        gcloud secrets versions access latest --secret=myistio-key-secret > tls.key

    - name: Create or update Kubernetes TLS secret
      run: |
        kubectl delete secret myistio-cert-secret -n istio-system --ignore-not-found
        kubectl create secret tls myistio-cert-secret \
          --cert=tls.crt \
          --key=tls.key \
          -n istio-system

    - name: Clean up local files
      run: rm tls.crt tls.key
